package cn.chao.maven.entity;

import java.util.Date;

public class CarouselEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.id
     *
     * @mbg.generated
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.imgUrl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.imgLink
     *
     * @mbg.generated
     */
    private String imglink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.sorting
     *
     * @mbg.generated
     */
    private Integer sorting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_carousel.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.id
     *
     * @return the value of tb_carousel.id
     *
     * @mbg.generated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.id
     *
     * @param id the value for tb_carousel.id
     *
     * @mbg.generated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.imgUrl
     *
     * @return the value of tb_carousel.imgUrl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.imgUrl
     *
     * @param imgurl the value for tb_carousel.imgUrl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.imgLink
     *
     * @return the value of tb_carousel.imgLink
     *
     * @mbg.generated
     */
    public String getImglink() {
        return imglink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.imgLink
     *
     * @param imglink the value for tb_carousel.imgLink
     *
     * @mbg.generated
     */
    public void setImglink(String imglink) {
        this.imglink = imglink == null ? null : imglink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.remark
     *
     * @return the value of tb_carousel.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.remark
     *
     * @param remark the value for tb_carousel.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.sorting
     *
     * @return the value of tb_carousel.sorting
     *
     * @mbg.generated
     */
    public Integer getSorting() {
        return sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.sorting
     *
     * @param sorting the value for tb_carousel.sorting
     *
     * @mbg.generated
     */
    public void setSorting(Integer sorting) {
        this.sorting = sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.status
     *
     * @return the value of tb_carousel.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.status
     *
     * @param status the value for tb_carousel.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.create_time
     *
     * @return the value of tb_carousel.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.create_time
     *
     * @param createTime the value for tb_carousel.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_carousel.update_time
     *
     * @return the value of tb_carousel.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_carousel.update_time
     *
     * @param updateTime the value for tb_carousel.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}