package cn.chao.maven.entity;

public class MenusEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.menu_id
     *
     * @mbg.generated
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.href
     *
     * @mbg.generated
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.perms
     *
     * @mbg.generated
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.spread
     *
     * @mbg.generated
     */
    private String spread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menus.sorting
     *
     * @mbg.generated
     */
    private Long sorting;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.menu_id
     *
     * @return the value of tb_menus.menu_id
     *
     * @mbg.generated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.menu_id
     *
     * @param menuId the value for tb_menus.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.title
     *
     * @return the value of tb_menus.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.title
     *
     * @param title the value for tb_menus.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.icon
     *
     * @return the value of tb_menus.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.icon
     *
     * @param icon the value for tb_menus.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.href
     *
     * @return the value of tb_menus.href
     *
     * @mbg.generated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.href
     *
     * @param href the value for tb_menus.href
     *
     * @mbg.generated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.perms
     *
     * @return the value of tb_menus.perms
     *
     * @mbg.generated
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.perms
     *
     * @param perms the value for tb_menus.perms
     *
     * @mbg.generated
     */
    public void setPerms(String perms) {
        this.perms = perms == null ? null : perms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.spread
     *
     * @return the value of tb_menus.spread
     *
     * @mbg.generated
     */
    public String getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.spread
     *
     * @param spread the value for tb_menus.spread
     *
     * @mbg.generated
     */
    public void setSpread(String spread) {
        this.spread = spread == null ? null : spread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.parent_id
     *
     * @return the value of tb_menus.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.parent_id
     *
     * @param parentId the value for tb_menus.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menus.sorting
     *
     * @return the value of tb_menus.sorting
     *
     * @mbg.generated
     */
    public Long getSorting() {
        return sorting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menus.sorting
     *
     * @param sorting the value for tb_menus.sorting
     *
     * @mbg.generated
     */
    public void setSorting(Long sorting) {
        this.sorting = sorting;
    }
}