package cn.chao.maven.entity;

public class RolesEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_roles.role_remark
     *
     * @mbg.generated
     */
    private String roleRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_id
     *
     * @return the value of tb_roles.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_id
     *
     * @param roleId the value for tb_roles.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_name
     *
     * @return the value of tb_roles.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_name
     *
     * @param roleName the value for tb_roles.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_roles.role_remark
     *
     * @return the value of tb_roles.role_remark
     *
     * @mbg.generated
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_roles.role_remark
     *
     * @param roleRemark the value for tb_roles.role_remark
     *
     * @mbg.generated
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }
}