package cn.chao.maven.mapper;

import cn.chao.maven.entity.AdminEntity;
import cn.chao.maven.entity.AdminEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    long countByExample(AdminEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int deleteByExample(AdminEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int insert(AdminEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int insertSelective(AdminEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    List<AdminEntity> selectByExample(AdminEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    AdminEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminEntity record, @Param("example") AdminEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminEntity record, @Param("example") AdminEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminEntity record);
}