package cn.chao.maven.mapper;

import cn.chao.maven.entity.CarouselEntity;
import cn.chao.maven.entity.CarouselEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarouselEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    long countByExample(CarouselEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int deleteByExample(CarouselEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int insert(CarouselEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int insertSelective(CarouselEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    List<CarouselEntity> selectByExample(CarouselEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    CarouselEntity selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CarouselEntity record, @Param("example") CarouselEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CarouselEntity record, @Param("example") CarouselEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CarouselEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_carousel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CarouselEntity record);
}