package cn.chao.maven.mapper;

import cn.chao.maven.entity.MenusEntity;
import cn.chao.maven.entity.MenusEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenusEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    long countByExample(MenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int deleteByExample(MenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int insert(MenusEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int insertSelective(MenusEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    List<MenusEntity> selectByExample(MenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    MenusEntity selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenusEntity record, @Param("example") MenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenusEntity record, @Param("example") MenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenusEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenusEntity record);
}