package cn.chao.maven.mapper;

import cn.chao.maven.entity.RolesEntity;
import cn.chao.maven.entity.RolesEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    long countByExample(RolesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int deleteByExample(RolesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int insert(RolesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int insertSelective(RolesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    List<RolesEntity> selectByExample(RolesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    RolesEntity selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolesEntity record, @Param("example") RolesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolesEntity record, @Param("example") RolesEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolesEntity record);
}