package cn.chao.maven.mapper;

import cn.chao.maven.entity.RolesMenusEntityExample;
import cn.chao.maven.entity.RolesMenusEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesMenusEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    long countByExample(RolesMenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    int deleteByExample(RolesMenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RolesMenusEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    int insert(RolesMenusEntityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    int insertSelective(RolesMenusEntityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    List<RolesMenusEntityKey> selectByExample(RolesMenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolesMenusEntityKey record, @Param("example") RolesMenusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles_menus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolesMenusEntityKey record, @Param("example") RolesMenusEntityExample example);
}