package cn.chao.maven.mapper;

import cn.chao.maven.entity.TestEntity;
import cn.chao.maven.entity.TestEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    long countByExample(TestEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int deleteByExample(TestEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int insert(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int insertSelective(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    List<TestEntity> selectByExample(TestEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    TestEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TestEntity record, @Param("example") TestEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TestEntity record, @Param("example") TestEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestEntity record);
}