package cn.chao.maven.mapper;

import cn.chao.maven.entity.UsersEntity;
import cn.chao.maven.entity.UsersEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    long countByExample(UsersEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int deleteByExample(UsersEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int insert(UsersEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int insertSelective(UsersEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    List<UsersEntity> selectByExample(UsersEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    UsersEntity selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UsersEntity record, @Param("example") UsersEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UsersEntity record, @Param("example") UsersEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UsersEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersEntity record);
}